### ISSUE TITLE
Support RGB colors from Discord

### ISSUE THREAD

**Issue by Parsonswy** [peacefulcraft-network/CowBot#8]
Right now we're mapping from RGB colors to the old hex codes. We can just pass the values over as straight RGB now instead of trying to translate.

**Comment by michaeljecmen** [comment]
Hey @Parsonswy, I have a working fix for this (ranks sent from Discord chat to MC chat will be correctly colored), but from some research ([link 1](https://www.codegrepper.com/code-examples/java/How+to+change+color+of+console+log+in+java), [link 2](https://stackoverflow.com/questions/53211694/change-color-and-format-of-java-util-logging-logger-output-in-eclipse)) it looks like making the colors work in the bungeecord console might be more difficult, if not impossible (could very likely be terminal-dependent).

I can take a look as well at this, but I thought it might be unimportant and lead to unnecessary code bloat to implement some kind of logging color formatter. What are your thoughts?

**Comment by michaeljecmen** [comment]
(either way, I'll open a PR for the changes as-is)

**Comment by michaeljecmen** [comment]
I should also be clear that the bungeecord colors appeared to not work before, so this enhancement isn't "breaking" them in any way.

**Comment by Parsonswy** [comment]
Yes - the console output its platform dependent. I am not certain which
applications/vendors are responsible for translation inconsistencies at an
OS level, but most of the web-based consoles in Pterodactyl, McMyAdmin, and
MultiCraft that we are targeting have explicit translation for MC color
codes so it should be fine.

**Comment by michaeljecmen** [comment]
Huh. Good to know. Further, I opened that PR without adding support for italics, bold, underlining, etc, which we had previously discussed. Would you still like that functionality implemented? If so, I'll make a new PR or update the existing one if it hasn't been closed by then.
